### ISSUE TITLE
DateTime issue with brand-new container

### ISSUE THREAD

**Issue by Knuppes** [zivillian/ism7mqtt#119]
Just created a parameter.json and started up the brand-new container. But I get some some DateTime Issues:

```docker logs 2196787ba2d5
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at ism7mqtt.ISM7.Xml.BM2DateConverterTemplate.AddTelegram(Byte low, Byte high) in /app/ism7mqtt/ISM7/Xml/BM2DateConverterTemplate.cs:line 18
   at ism7mqtt.ISM7.Xml.SingleTelegramConverterTemplateBase.AddTelegram(UInt16 telegram, Byte low, Byte high) in /app/ism7mqtt/ISM7/Xml/SingleTelegramConverterTemplateBase.cs:line 24
   at ism7mqtt.Ism7Config.RunningParameter.ProcessDatapoint(UInt16 telegram, Nullable`1 service, Byte low, Byte high, Boolean write) in /app/ism7mqtt/ISM7/Ism7Config.cs:line 350
   at ism7mqtt.Ism7Config.RunningDevice.ProcessDatapoint(UInt16 telegram, Nullable`1 service, Byte low, Byte high, Boolean write) in /app/ism7mqtt/ISM7/Ism7Config.cs:line 226
   at ism7mqtt.Ism7Config.ProcessData(IEnumerable`1 data) in /app/ism7mqtt/ISM7/Ism7Config.cs:line 101
   at ism7mqtt.Ism7Client.OnInitialValuesAsync(IResponse response, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 324
   at ism7mqtt.ResponseDispatcher.DispatchAsync(IResponse response, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/ResponseDispatcher.cs:line 32
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 213
System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
```
Am I missing something?

**Comment by Knuppes** [comment]
Hmm, maybe it's because the returned value is empty? It's just a guess... And how can I fill this? iSM7 seems not to know anything about chrony or ntp...

> <?xml version="1.0" encoding="utf-8"?><direct-logon-request><password>XXXX</password></direct-logon-request>
< <direct-logon-response state="ok" sid="1">
  <installationname>Wolf Link</installationname>
  <serialnumber>XXXX</serialnumber>
  <date-time></date-time>
  <ism-softwareversion>4.40</ism-softwareversion>
  <ism-hardwareversion>linkr-4</ism-hardwareversion>
  <wlan-connected>false</wlan-connected>
  <type>Link</type>
</direct-logon-response>

**Comment by zivillian** [comment]
your stacktrace does not look like the `direct-logon-response` is the problem. Can you share the debug log?

**Comment by Knuppes** [comment]
The container I permanently restarting, so I can only get the docker logs output, I hope this is enough...
[Uploading debug.log…]()

**Comment by Knuppes** [comment]
Oh man. I found it. Date and Time was not set at all. I just set it and stuff is coming into my MQTT...

I had the system disconnected from power for some weeks, at least for a so long time of power off, it forgets this...

Sorry I bothered you. But maybe this is helpful for other guys as stupid as me...

**Comment by zivillian** [comment]
The log file looks promising - thanks for reporting. Even though you found and fixed your issue, I'd like to implement a check and warning to tell others to set the correct time...
