### ISSUE TITLE
System.InvalidOperationException: <direct-logon-response xmlns=''> was not expected.

### ISSUE THREAD

**Issue by mchrusto** [zivillian/ism7mqtt#136]
Hello 
I am using ism7 with version 2.10, once I started addon for the very first time  config file is created with out any problems -  file is attached. Once addon  is trying to restart using config file I am getting following error (see also attached log file):

```
Oct 10 21:25:37 Publishing HA Discovery info for ID Wolf
Oct 10 21:25:37 < <?xml version="1.0" encoding="utf-8"?><direct-logon-response state="ok" sid="1"><installationname>ISM7</installationname><serialnumber>d88039b74cda</serialnumber><date-time>2024-10-10T21:25:59</date-time><ism-softwareversion>210.46.1.5.2.1</ism-softwareversion><ism-hardwareversion>1.0</ism-hardwareversion><type>ISM7i</type></direct-logon-response>
Oct 10 21:25:37 System.InvalidOperationException: There is an error in XML document (1, 40).
Oct 10 21:25:37  ---> System.InvalidOperationException: <direct-logon-response xmlns=''> was not expected.
Oct 10 21:25:37    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderTelegramBundleResp.Read6_tbres()
Oct 10 21:25:37    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
Oct 10 21:25:37    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Oct 10 21:25:37    --- End of inner exception stack trace ---
Oct 10 21:25:37    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
Oct 10 21:25:37    at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
Oct 10 21:25:37    at ism7mqtt.Ism7Client.Deserialize(PayloadType type, Stream data) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 381
Oct 10 21:25:37    at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 190
Oct 10 21:25:37 System.Net.Sockets.SocketException (125): Operation canceled
Oct 10 21:25:37    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
Oct 10 21:25:37    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
Oct 10 21:25:37    at ism7ssl.Ism7SslStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in /app/ism7ssl/Ism7SslStream.cs:line 154
Oct 10 21:25:37    at ism7mqtt.Ism7Client.FillPipeAsync(PipeWriter target, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 145
```

I did try to clean everything and reinstall addon but I am getting always same error.
What could be wrong here? Thx a lot for your support & regards

[ism7-parameters-Wolf.json](https://github.com/user-attachments/files/17333107/ism7-parameters-Wolf.json)
![Wolf_ISM7_Home_Assistant](https://github.com/user-attachments/assets/5c56a8fa-0aa8-4208-9b9c-43978d81f3a5)
[Wolf_ISM7_Log.txt](https://github.com/user-attachments/files/17333108/Wolf_ISM7_Log.txt)

**Comment by mchrusto** [comment]
Hello 
I did install ism7mqtt on linux machine and run with debug option -  please see attached log file. Still getting error  _System.InvalidOperationException: <direct-logon-response xmlns=''> was not expected._ 
[ism7mqtt.log](https://github.com/user-attachments/files/17441451/ism7mqtt.log)
Any idea why is this happening, I am also attaching parameter.json file that I did create
[parameter.json](https://github.com/user-attachments/files/17441469/parameter.json)
 by ism7config , thank you for your support

**Comment by zivillian** [comment]
The log shows a second `<direct-logon-response` after ism7mqtt already received the first and sent the initial requests. It has the exact same timestamp, but is there a delay before the error occurs?
Can you try again with a reduced parameter.json like this one?
```json
{
  "TcpPort": 9092,
  "Devices": [
    {
      "ReadBusAddress": "0x35",
      "WriteBusAddress": "0x30",
      "DeviceTemplateId": 220000,
      "Parameter": [
        220032
      ]
    }
  ]
}
```
This should only report the time of the BM-2

**Comment by mchrusto** [comment]
Thx a lot, I did test it and yes this is working  - as you wrote I am getting time of the BM-2.
Here is the log file 
[ism7mqtt.log](https://github.com/user-attachments/files/17457274/ism7mqtt.log)

**Comment by zivillian** [comment]
Then you can try to readd the parameters until you get the error again - to me it looks like one of the parameters is causing this.

**Comment by mchrusto** [comment]
Thx a lot I did  and did find out that the last section a parameters 360000 and above are creating this problem. Once I delete them from parameter.json things are working  ok. What is actually behind 360000?
 
![image](https://github.com/user-attachments/assets/c4141e21-0414-434d-a122-f12cbf98ea78)

**Comment by zivillian** [comment]
DeviceTemplate `360000` belongs to `MK_BM-2`. The ParameterIds can be looked up in the [ParameterTemplates.xml](https://github.com/zivillian/ism7mqtt/blob/29f9e43de8ef65711cad0c2a32905730e4cbf991/src/ism7mqtt/Resources/ParameterTemplates.xml):
```
360000: Raumtemperatur
360001:Gemittelte Außentemperatur
360004:Anforderung Mischerkreis
...
360148:Starttemperatur VL Kühlkurve
360149:Endpunkt Kühlkurve
360150:Startpunkt Kühlkurve
```
Can you try to narrow it down to one (or some) parameters?

**Comment by Adi146** [comment]
Looks like just `360000` is the problem, everything else works for me

**Comment by mchrusto** [comment]
Yes I can confirm 360000 is the problem -  anything with 360xxx

**Comment by zivillian** [comment]
Can you check if the official Smartset app works for you and also reports the affected parameters?

**Comment by chrissi323** [comment]
Hi,

I have the same problem while trying to make this work with an ISM7 FW-Version 2.00, however it's not triggered by a single or a set of parameters. 

This ism7-parameters.json works but does not have all devices:

[ism7-parameters-Wolf_Heizung good.json](https://github.com/user-attachments/files/21410248/ism7-parameters-Wolf_Heizung.good.json)

This one with only one device also works:

[ism7-parameters-Wolf_Heizung Test.json](https://github.com/user-attachments/files/21410322/ism7-parameters-Wolf_Heizung.Test.json)

But, if i combine this two working files to:

[ism7-parameters-Wolf_Heizung combined.json](https://github.com/user-attachments/files/21410407/ism7-parameters-Wolf_Heizung.combined.json)

I get:

`Starting ism7mqtt --hass-id=Wolf_Heizung --interval=60 --ipAddress=192.168.168.22 -t /config/ism7-parameters-Wolf_Heizung.json
Jul 24 13:47:50 System.InvalidOperationException: There is an error in XML document (1, 40).
Jul 24 13:47:50  ---> System.InvalidOperationException: <direct-logon-response xmlns=''> was not expected.
Jul 24 13:47:50    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderTelegramBundleResp.Read6_tbres()
Jul 24 13:47:50    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
Jul 24 13:47:50    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Jul 24 13:47:50    --- End of inner exception stack trace ---
Jul 24 13:47:50    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
Jul 24 13:47:50    at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
Jul 24 13:47:50    at ism7mqtt.Ism7Client.Deserialize(PayloadType type, Stream data) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 381
Jul 24 13:47:50    at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 190
Jul 24 13:47:50 System.Net.Sockets.SocketException (125): Operation canceled
Jul 24 13:47:50    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
Jul 24 13:47:50    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
Jul 24 13:47:50    at ism7ssl.Ism7SslStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in /app/ism7ssl/Ism7SslStream.cs:line 154
Jul 24 13:47:50    at ism7mqtt.Ism7Client.FillPipeAsync(PipeWriter target, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 145`

I have no idea how to proceed from here. Reducing the numer of parameters doesn't help, it also doesn't seem to be a problem of the number of devices, maybe they some combinations can not be queried from the ISM7 simultaneously?

On side note, all sensors in the ISM devices like "Ip Adress" or "Default Gateway" have the state unknown. Other devices seem to get updates.

I get the feeling the ISM7 is very unreliable and I maybe should consider an ebus adapter....

Any ideas would be very welcome!

Thanks!

**Comment by c-worm** [comment]
This is quite a coincident. I figured out, that the number of values is an issue and had it running.... until yesterday. Out of the blue the error was back.

This time I had to remove this to make it work again:

    {
      "ReadBusAddress": "0x75",
      "WriteBusAddress": "0x70",
      "DeviceTemplateId": 30000,
      "Parameter": [
        30000
      ]
    }

Couldn't figure out which device that is, for now it works again. Also I noticed that I couldn#t set values even if the error doesn't occur and reading the values works. This also seems to be an indicator for a struggeling ISM7.

I also updated to the most recent version (v0.0.19-1) of the addon but had to downgrade the to  v0.0.17 because of [this](https://github.com/b3nn0/hassio-addon-ism7mqtt/issues/105). I had deleted the MQTT devices to see which one I had removed by deleting the lines above and and the newly created entities were all unnamed and I couldn't set a value.
