### ISSUE TITLE
SSL | Authentication failed

### ISSUE THREAD

**Issue by dev-da77** [zivillian/ism7mqtt#45]
I run the following command on an ARCHLINUXARM device:

`./ism7mqtt -m <homeassistant ip> -i <ism7 ip> -p <ism7 password> -t ../parameter.json --mqttuser=<homeassistant mqtt user> --mqttpass=<homeassistant mqtt password>`

My MQTT server is at my homeassistant device (mosquitto broker).

And I have trouble with SSL:

```
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0A000152:SSL routines::unsafe legacy renegotiation disabled
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle , ReadOnlySpan`1 , Byte[]& , Int32& )
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials , SafeDeleteSslContext& , ReadOnlySpan`1 , Byte[]& , SslAuthenticationOptions )
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boolean )
   at ism7mqtt.Ism7Client.ConnectAsync(CancellationToken cancellationToken) in /home/runner/work/ism7mqtt/ism7mqtt/src/ism7mqtt/ISM7/Ism7Client.cs:line 87
   at ism7mqtt.Ism7Client.RunAsync(String password, CancellationToken cancellationToken) in /home/runner/work/ism7mqtt/ism7mqtt/src/ism7mqtt/ISM7/Ism7Client.cs:line 51
   at ism7mqtt.Program.Main(String[] args) in /home/runner/work/ism7mqtt/ism7mqtt/src/ism7mqtt/Program.cs:line 131
Unhandled exception. System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0A000152:SSL routines::unsafe legacy renegotiation disabled
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle , ReadOnlySpan`1 , Byte[]& , Int32& )
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials , SafeDeleteSslContext& , ReadOnlySpan`1 , Byte[]& , SslAuthenticationOptions )
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boolean )
   at ism7mqtt.Ism7Client.ConnectAsync(CancellationToken cancellationToken) in /home/runner/work/ism7mqtt/ism7mqtt/src/ism7mqtt/ISM7/Ism7Client.cs:line 87
   at ism7mqtt.Ism7Client.RunAsync(String password, CancellationToken cancellationToken) in /home/runner/work/ism7mqtt/ism7mqtt/src/ism7mqtt/ISM7/Ism7Client.cs:line 51
   at ism7mqtt.Program.Main(String[] args) in /home/runner/work/ism7mqtt/ism7mqtt/src/ism7mqtt/Program.cs:line 131
   at ism7mqtt.Program.<Main>(String[] args)
Abgebrochen (Speicherabzug geschrieben)
```

*.crt of HOMEASSISTANT (self-signed) is known by ARCHLINUXARM device (sudo trust anchor --store <***>.crt)

**Comment by zivillian** [comment]
You need to enable [unsafe legacy renegotiation](https://stackoverflow.com/a/72245418/19671). You need to create an [openssl.cnf](https://github.com/zivillian/ism7mqtt/blob/master/openssl.cnf) file and either set an env variable (e.g. in your ism7mqtt.service) `OPENSSL_CONF=/path/to/your/openssl.cnf` or prefix your command with
```sh
$ OPENSSL_CONF=/path/to/your/openssl.cnf ./ism7mqtt -m <homeassistant ip> ...
```

**Comment by dev-da77** [comment]
That's it. Thank you. I receive data now :-)
