### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by wartungsmonteur** [zivillian/ism7mqtt#61]
Hallo

ich bekomme nach dem Start des Plugin folgende Fehlermeldung:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
++ cd /app
Creating initial configuration /config/ism7-parameters-Wolf.json
++ parameters=/config/ism7-parameters-Wolf.json
++ '[' -f /config/ism7-parameters-Wolf.json ']'
++ echo 'Creating initial configuration /config/ism7-parameters-Wolf.json'
++ /app/ism7config -t /config/ism7-parameters-Wolf.json
2023-06-29 13:22:32.0172|INFO|LuCon.WebPortal.StandaloneService.NetworkConnector|Try IP-resolve for host:192.168.178.84
2023-06-29 13:22:32.0846|INFO|LuCon.WebPortal.StandaloneService.NetworkConnector|Try connect destination server -> 192.168.178.84:9092, Timeout:1000 ms
2023-06-29 13:22:37.3709|ERROR|LuCon.WebPortal.StandaloneService.NetworkConnector|DoConnect
Unhandled exception. LuCon.Common.Declarations.BusinessServiceException: Die Verbindung zur Anlage kann nicht hergestellt werden. Aktualisieren Sie die Anlagenliste und versuchen Sie es nochmal.
   at LuCon.WebPortal.StandaloneService.NetworkConnector.DoConnect(String server, IPAddress localIp, Int32 port, String password, IStreamHandler streamHandler)
   at ism7config.Program.Main(String[] args) in /app/ism7config/Program.cs:line 120
   at ism7config.Program.<Main>(String[] args)
/run.sh: line 28:   125 Aborted                 (core dumped) /app/ism7config -t $parameters
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by zivillian** [comment]
I've published a new version with increased timeouts. As soon as the HA Addon is updated, you can try again.

**Comment by wartungsmonteur** [comment]
Hallo

Läuft leider noch nicht: Jetzt stoppt das Plugin mit folgender Meldung:

    <irs se="A;284" ba="0x76" in="2704" dl="0x0" dh="0x0" st="OK"/>
    <irs se="A;157" ba="0x35" in="10150" dl="0x0" dh="0x0" st="OK"/>
    <irs se="A;259" ba="0x76" in="2601" dl="0xC2" dh="0x2" st="OK"/>
    <irs se="A;231" ba="0x52" in="2602" dl="0x89" dh="0x2" st="OK"/>
    <irs se="A;72" ba="0x8" in="2" dl="0x32" dh="0x0" st="OK"/>
    <irs se="A;258" ba="0x76" in="2701" dl="0x0" dh="0x0" st="OK"/>
    <irs se="A;366" ba="0x85" in="10156" dl="0x0" dh="0x0" st="OK"/>
    <irs se="A;412" ba="0x86" in="10156" dl="0x0" dh="0x0" st="OK"/>
    <irs se="A;458" ba="0x87" in="10156" dl="0x0" dh="0x0" st="OK"/>
    <irs se="A;495" ba="0x35" in="19" dl="0xC2" dh="0x1" st="OK"/>
    <irs se="B;360;363" ba="0x85" in="10164" dl="0x0" dh="0x80" st="OK"/>
    <irs se="A;261" ba="0x76" in="2605" dl="0xCA" dh="0x2" st="OK"/>
    <irs se="A;186" ba="0x35" in="10157" dl="0x1" dh="0x0" st="OK"/>
    <irs se="A;152" ba="0x35" in="10152" dl="0xD0" dh="0x2E" st="OK"/>
    <irs se="B;361;359;367" ba="0x85" in="10109" dl="0xC8" dh="0x0" st="OK"/>
    <irs se="A;496" ba="0x35" in="10101" dl="0x1" dh="0x0" st="OK"/>
    </tbres>
2023-07-17 18:55:49.0577|INFO|GW-1|<GW:1,0> Written XML, bytes:1025, msg:<?xml version="1.0" encoding="utf-8"?>
    <tbreq bn="1002" gw="1" ae="true" ty="push">
    <ird se="B;452;455" ba="0x87" in="10164" is="60" />
    <ird se="A;154" ba="0x35" in="10154" is="60" />
    <ird se="A;191" ba="0x35" in="10117" is="60" />
    <ird se="A;69" ba="0x8" in="328" is="60" />
    <ird se="B;156;163" ba="0x35" in="10160" is="60" />
    <ird se="A;262" ba="0x76" in="132" is="60" />
    <ird se="A;364" ba="0x85" in="10119" is="60" />
    <ird se="A;410" ba="0x86" in="10119" is="60" />
    <ird se="A;456" ba="0x87" in="10119" is="60" />
    <ird se="B;413;405;407" ba="0x86" in="10109" is="60" />
    <ird se="A;71" ba="0x8" in="10068" is="60" />
    <ird se="A;159" ba="0x35" in="10147" is="60" />
    <ird se="A;85" ba="0x8" in="14" is="60" />
    <ird se="A;520" ba="0x35" in="5249" is="60" />
    <ird se="A;78" ba="0x8" in="12" is="60" />
    <ird se="A;161" ba="0x35" in="10149" is="60" />
    <ird se="A;79" ba="0x8" in="22" is="60" />
    <ird se="A;74" ba="0x8" in="10007" is="60" />
    <ird se="A;519" ba="0x35" in="10158" is="60" />
    <ird se="A;283" ba="0x76" in="2703" is="60" />
    </tbreq>
2023-07-17 18:56:07.3695|TRACE|GW-1|<GW:1,0> ReadTelegramAsync !!
2023-07-17 18:56:07.3695|TRACE|GW-1|<GW:1,0> Got 6 bytes from stream, elapsedMs=0
2023-07-17 18:56:07.3695|TRACE|GW-1|<GW:1,0> lenToRead: 313
2023-07-17 18:56:07.3695|TRACE|GW-1|<GW:1,0> telegrType TgrBundleResponse
2023-07-17 18:56:07.3695|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:313 [6/313]
2023-07-17 18:56:07.4130|TRACE|GW-1|<GW:1,0> Got 241 bytes from stream, elapsedMs=43
2023-07-17 18:56:07.4130|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:72 [247/313]
2023-07-17 18:56:07.4147|TRACE|GW-1|<GW:1,0> Got 64 bytes from stream, elapsedMs=45
2023-07-17 18:56:07.4147|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:8 [311/313]
2023-07-17 18:56:07.4579|TRACE|GW-1|<GW:1,0> Got 8 bytes from stream, elapsedMs=88
2023-07-17 18:56:07.4579|INFO|GW-1|<GW:1,0> Got XML msg:???<?xml version="1.0" encoding="utf-8"?>
    <tbres bn="1002" gw="1" st="OK" ts="2023-07-17T18:56:37" emsg="">
    <irs se="B;452;455" ba="0x87" in="10164" dl="0x0" dh="0x80" st="OK"/>
    <irs se="A;154" ba="0x35" in="10154" dl="0xD0" dh="0x2E" st="OK"/>
    <irs se="A;191" ba="0x35" in="10117" dl="0x0" dh="0x0" st="OK"/>
    </tbres>
2023-07-17 18:56:07.4592|INFO|GW-1|<GW:1,0> Written XML, bytes:1044, msg:<?xml version="1.0" encoding="utf-8"?>
    <tbreq bn="1003" gw="1" ae="true" ty="push">
    <ird se="C;215;86;87" ba="0x51" in="86" is="60" />
    <ird se="C;215;86;87" ba="0x51" in="87" is="60" />
    <ird se="C;227;86;87" ba="0x52" in="86" is="60" />
    <ird se="C;227;86;87" ba="0x52" in="87" is="60" />
    <ird se="C;245;86;87" ba="0x53" in="86" is="60" />
    <ird se="C;245;86;87" ba="0x53" in="87" is="60" />
    <ird se="A;75" ba="0x8" in="367" is="60" />
    <ird se="B;409;406" ba="0x86" in="10164" is="60" />
    <ird se="C;80;551;550" ba="0x8" in="551" is="60" />
    <ird se="C;80;551;550" ba="0x8" in="550" is="60" />
    <ird se="A;92" ba="0x8" in="10013" is="60" />
    <ird se="A;81" ba="0x8" in="554" is="60" />
    <ird se="A;285" ba="0x76" in="2603" is="60" />
    <ird se="A;164" ba="0x35" in="10145" is="60" />
    <ird se="A;58" ba="0x8" in="370" is="60" />
    <ird se="A;260" ba="0x76" in="2602" is="60" />
    <ird se="A;286" ba="0x76" in="2604" is="60" />
    <ird se="A;44" ba="0x85" in="10155" is="60" />
    <ird se="A;217" ba="0x51" in="15" is="60" />
    <ird se="A;49" ba="0x86" in="10155" is="60" />
    </tbreq>
2023-07-17 18:56:07.8493|TRACE|GW-1|<GW:1,0> ReadTelegramAsync !!
2023-07-17 18:56:07.8493|TRACE|GW-1|<GW:1,0> Got 6 bytes from stream, elapsedMs=0
2023-07-17 18:56:07.8493|TRACE|GW-1|<GW:1,0> lenToRead: 0
2023-07-17 18:56:07.8493|TRACE|GW-1|<GW:1,0> telegrType TgrBundleResponse
2023-07-17 18:56:07.8493|INFO|GW-1|<GW:1,0> Got XML msg:
2023-07-17 18:56:07.8522|ERROR|GW-1|<GW:1,-1>
2023-07-17 18:56:07.8529|INFO|GW-1|<GW:1,0> Close
2023-07-17 18:56:07.8881|DEBUG|LuCon.SocketServer.GatewayInterface.Util|CloseTcpClient
Timeout waiting for GW
Parameter file creation seems to have failed. Please report to the ism7mqtt project: https://github.com/zivillian/ism7mqtt/issues/new
++ '[' -f /config/ism7-parameters-Wolf.json ']'
++ echo 'Parameter file creation seems to have failed. Please report to the ism7mqtt project: https://github.com/zivillian/ism7mqtt/issues/new'
++ exit -1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by wartungsmonteur** [comment]
Hallo

Läuft länger aber stoppt dann wieder.

    <ird se="A;77" ba="0x8" in="10010" is="60" />
    <ird se="A;76" ba="0x8" in="10071" is="60" />
    <ird se="A;228" ba="0x52" in="2701" is="60" />
    <ird se="A;358" ba="0x85" in="10179" is="60" />
    <ird se="A;404" ba="0x86" in="10179" is="60" />
    </tbreq>
2023-07-17 19:38:47.9200|TRACE|GW-1|<GW:1,0> ReadTelegramAsync !!
2023-07-17 19:38:47.9200|TRACE|GW-1|<GW:1,0> Got 6 bytes from stream, elapsedMs=0
2023-07-17 19:38:47.9200|TRACE|GW-1|<GW:1,0> lenToRead: 86
2023-07-17 19:38:47.9200|TRACE|GW-1|<GW:1,0> telegrType TgrBundleResponse
2023-07-17 19:38:47.9200|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:86 [6/86]
2023-07-17 19:38:47.9643|TRACE|GW-1|<GW:1,0> Got 86 bytes from stream, elapsedMs=44
2023-07-17 19:38:47.9643|INFO|GW-1|<GW:1,0> Got XML msg:???<?xml version="1.0" encoding="utf-8"?>
    <tbres bn="3" gw="1" st="OK" emsg="">
    </tbres>
2023-07-17 19:39:07.2592|TRACE|GW-1|<GW:1,0> ReadTelegramAsync !!
2023-07-17 19:39:07.2592|TRACE|GW-1|<GW:1,0> Got 6 bytes from stream, elapsedMs=0
2023-07-17 19:39:07.2592|TRACE|GW-1|<GW:1,0> lenToRead: 1450
2023-07-17 19:39:07.2592|TRACE|GW-1|<GW:1,0> telegrType TgrBundleResponse
2023-07-17 19:39:07.2592|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:1450 [6/1450]
2023-07-17 19:39:07.2641|TRACE|GW-1|<GW:1,0> Got 249 bytes from stream, elapsedMs=4
2023-07-17 19:39:07.2641|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:1201 [255/1450]
2023-07-17 19:39:07.2722|TRACE|GW-1|<GW:1,0> Got 66 bytes from stream, elapsedMs=12
2023-07-17 19:39:07.2722|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:1135 [321/1450]
2023-07-17 19:39:07.2743|TRACE|GW-1|<GW:1,0> Got 225 bytes from stream, elapsedMs=15
2023-07-17 19:39:07.2743|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:910 [546/1450]
2023-07-17 19:39:07.2769|TRACE|GW-1|<GW:1,0> Got 64 bytes from stream, elapsedMs=17
2023-07-17 19:39:07.2769|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:846 [610/1450]
2023-07-17 19:39:07.2821|TRACE|GW-1|<GW:1,0> Got 197 bytes from stream, elapsedMs=22
2023-07-17 19:39:07.2821|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:649 [807/1450]
2023-07-17 19:39:07.2836|TRACE|GW-1|<GW:1,0> Got 64 bytes from stream, elapsedMs=24
2023-07-17 19:39:07.2836|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:585 [871/1450]
2023-07-17 19:39:07.2879|TRACE|GW-1|<GW:1,0> Got 194 bytes from stream, elapsedMs=28
2023-07-17 19:39:07.2879|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:391 [1065/1450]
2023-07-17 19:39:07.2896|TRACE|GW-1|<GW:1,0> Got 65 bytes from stream, elapsedMs=30
2023-07-17 19:39:07.2896|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:326 [1130/1450]
2023-07-17 19:39:07.3013|TRACE|GW-1|<GW:1,0> Got 188 bytes from stream, elapsedMs=42
2023-07-17 19:39:07.3013|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:138 [1318/1450]
2023-07-17 19:39:07.3033|TRACE|GW-1|<GW:1,0> Got 65 bytes from stream, elapsedMs=44
2023-07-17 19:39:07.3033|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:73 [1383/1450]
2023-07-17 19:39:07.3482|TRACE|GW-1|<GW:1,0> Got 73 bytes from stream, elapsedMs=88
2023-07-17 19:39:07.3482|INFO|GW-1|<GW:1,0> Got XML msg:???<?xml version="1.0" encoding="utf-8"?>
    <tbres bn="1000" gw="1" st="OK" ts="2023-07-17T19:39:36" emsg="">
    <irs se="B;60;59;61;62" ba="0x8" in="371" dl="0x40" dh="0x0" st="OK"/>
    <irs se="B;459;453;451" ba="0x87" in="10109" dl="0xC8" dh="0x0" st="OK"/>
    <irs se="A;160" ba="0x35" in="10148" dl="0x25" dh="0x13" st="OK"/>
    <irs se="C;264;135;136;137" ba="0x76" in="135" dl="0x81" dh="0x2" st="OK"/>
    <irs se="C;264;135;136;137" ba="0x76" in="136" dl="0x7A" dh="0x2" st="OK"/>
    <irs se="C;264;135;136;137" ba="0x76" in="137" dl="0x4E" dh="0x0" st="OK"/>
    <irs se="A;187" ba="0x35" in="5250" dl="0xF" dh="0x2F" st="OK"/>
    <irs se="A;42" ba="0x35" in="10134" dl="0x6" dh="0x0" st="OK"/>
    <irs se="B;162;155" ba="0x35" in="10161" dl="0x26" dh="0x13" st="OK"/>
    <irs se="A;389" ba="0x85" in="10159" dl="0x1" dh="0x0" st="OK"/>
    <irs se="A;435" ba="0x86" in="10159" dl="0x1" dh="0x0" st="OK"/>
    <irs se="A;481" ba="0x87" in="10159" dl="0x1" dh="0x0" st="OK"/>
    <irs se="B;214;213" ba="0x51" in="82" dl="0x0" dh="0x0" st="OK"/>
    <irs se="B;226;225" ba="0x52" in="82" dl="0x0" dh="0x0" st="OK"/>
    <irs se="B;244;243" ba="0x53" in="82" dl="0x0" dh="0x0" st="OK"/>
    <irs se="A;77" ba="0x8" in="10010" dl="0xC3" dh="0x0" st="OK"/>
    <irs se="A;76" ba="0x8" in="10071" dl="0x0" dh="0x0" st="OK"/>
    <irs se="A;228" ba="0x52" in="2701" dl="0x1" dh="0x0" st="OK"/>
    <irs se="A;358" ba="0x85" in="10179" dl="0xFF" dh="0x0" st="OK"/>
    <irs se="A;404" ba="0x86" in="10179" dl="0xFF" dh="0x0" st="OK"/>
    </tbres>
2023-07-17 19:39:07.3538|INFO|GW-1|<GW:1,0> Written XML, bytes:1041, msg:<?xml version="1.0" encoding="utf-8"?>
    <tbreq bn="1001" gw="1" ae="true" ty="push">
    <ird se="A;450" ba="0x87" in="10179" is="60" />
    <ird se="A;230" ba="0x52" in="2601" is="60" />
    <ird se="C;82;553;552" ba="0x8" in="553" is="60" />
    <ird se="C;82;553;552" ba="0x8" in="552" is="60" />
    <ird se="A;284" ba="0x76" in="2704" is="60" />
    <ird se="A;157" ba="0x35" in="10150" is="60" />
    <ird se="A;259" ba="0x76" in="2601" is="60" />
    <ird se="A;231" ba="0x52" in="2602" is="60" />
    <ird se="A;72" ba="0x8" in="2" is="60" />
    <ird se="A;258" ba="0x76" in="2701" is="60" />
    <ird se="A;366" ba="0x85" in="10156" is="60" />
    <ird se="A;412" ba="0x86" in="10156" is="60" />
    <ird se="A;458" ba="0x87" in="10156" is="60" />
    <ird se="A;495" ba="0x35" in="19" is="60" />
    <ird se="B;360;363" ba="0x85" in="10164" is="60" />
    <ird se="A;261" ba="0x76" in="2605" is="60" />
    <ird se="A;186" ba="0x35" in="10157" is="60" />
    <ird se="A;152" ba="0x35" in="10152" is="60" />
    <ird se="B;361;359;367" ba="0x85" in="10109" is="60" />
    <ird se="A;496" ba="0x35" in="10101" is="60" />
    </tbreq>
Timeout waiting for GW
Parameter file creation seems to have failed. Please report to the ism7mqtt project: https://github.com/zivillian/ism7mqtt/issues/new
++ '[' -f /config/ism7-parameters-Wolf.json ']'
++ echo 'Parameter file creation seems to have failed. Please report to the ism7mqtt project: https://github.com/zivillian/ism7mqtt/issues/new'
++ exit -1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping

**Comment by zivillian** [comment]
magst du einmal das vollständige Log hochladen? Und es wäre super, wenn du das einmal ohne den Docker Container mit den [Binaries aus dem Release](https://github.com/zivillian/ism7mqtt/releases/tag/v0.0.14) ausprobieren könntest. Dadurch können wir ausschließen, dass es irgendwas im HomeAssistant oder dem Addon ist.

**Comment by wartungsmonteur** [comment]
<ird se="A;52" ba="0x86" in="9028" is="60" />
    <ird se="A;45" ba="0x85" in="9024" is="60" />
    <ird se="A;57" ba="0x87" in="9028" is="60" />
    <ird se="A;50" ba="0x86" in="9024" is="60" />
    <ird se="A;55" ba="0x87" in="9024" is="60" />
    </tbreq>
2023-07-17 20:21:16.3484|TRACE|GW-1|<GW:1,0> ReadTelegramAsync !!
2023-07-17 20:21:16.3484|TRACE|GW-1|<GW:1,0> Got 6 bytes from stream, elapsedMs=0
2023-07-17 20:21:16.3484|TRACE|GW-1|<GW:1,0> lenToRead: 784
2023-07-17 20:21:16.3484|TRACE|GW-1|<GW:1,0> telegrType TgrBundleResponse
2023-07-17 20:21:16.3484|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:784 [6/784]
2023-07-17 20:21:16.3914|TRACE|GW-1|<GW:1,0> Got 192 bytes from stream, elapsedMs=42
2023-07-17 20:21:16.3914|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:592 [198/784]
2023-07-17 20:21:16.3981|TRACE|GW-1|<GW:1,0> Got 43 bytes from stream, elapsedMs=49
2023-07-17 20:21:16.3981|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:549 [241/784]
2023-07-17 20:21:16.3999|TRACE|GW-1|<GW:1,0> Got 150 bytes from stream, elapsedMs=51
2023-07-17 20:21:16.3999|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:399 [391/784]
2023-07-17 20:21:16.4018|TRACE|GW-1|<GW:1,0> Got 62 bytes from stream, elapsedMs=53
2023-07-17 20:21:16.4018|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:337 [453/784]
2023-07-17 20:21:16.4071|TRACE|GW-1|<GW:1,0> Got 153 bytes from stream, elapsedMs=58
2023-07-17 20:21:16.4071|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:184 [606/784]
2023-07-17 20:21:16.4088|TRACE|GW-1|<GW:1,0> Got 44 bytes from stream, elapsedMs=60
2023-07-17 20:21:16.4088|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:140 [650/784]
2023-07-17 20:21:16.4140|TRACE|GW-1|<GW:1,0> Got 132 bytes from stream, elapsedMs=65
2023-07-17 20:21:16.4140|TRACE|GW-1|<GW:1,0> Try to complete msg, bytesMissing:8 [782/784]
2023-07-17 20:21:16.4157|TRACE|GW-1|<GW:1,0> Got 8 bytes from stream, elapsedMs=67
2023-07-17 20:21:16.4160|INFO|GW-1|<GW:1,0> Got XML msg:???<?xml version="1.0" encoding="utf-8"?>
    <tbres bn="11" gw="1" st="OK" ts="2166-01-01T00:00:33" emsg="">
    <irs se="A;48" ba="0x86" in="5266" st="ER"/>
    <irs se="A;53" ba="0x87" in="5266" st="ER"/>
    <irs se="A;30" ba="0x51" in="410" st="ER"/>
    <irs se="A;31" ba="0x52" in="410" st="ER"/>
    <irs se="A;32" ba="0x53" in="410" st="ER"/>
    <irs se="B;17;23" ba="0x8" in="410" dl="0xE6" dh="0x0" st="OK"/>
    <irs se="A;19" ba="0x8" in="10878" dl="0x0" dh="0x0" st="OK"/>
    <irs se="B;38;37" ba="0x76" in="2476" dl="0x1" dh="0x0" st="OK"/>
    <irs se="A;47" ba="0x85" in="9028" st="ER"/>
    <irs se="A;52" ba="0x86" in="9028" st="ER"/>
    <irs se="A;45" ba="0x85" in="9024" st="ER"/>
    <irs se="A;57" ba="0x87" in="9028" st="ER"/>
    <irs se="A;50" ba="0x86" in="9024" st="ER"/>
    <irs se="A;55" ba="0x87" in="9024" st="ER"/>
    </tbres>
2023-07-17 20:21:16.4160|WARN|GW-1|<GW:1,-1> - Response state:ER !!! entry:Resp -> Seq:A;48, Ba:0x86, TelegrNr:5266, State:ER, set value to null
2023-07-17 20:21:16.4160|WARN|GW-1|<GW:1,-1> - Response state:ER !!! entry:Resp -> Seq:A;53, Ba:0x87, TelegrNr:5266, State:ER, set value to null
2023-07-17 20:21:16.4169|WARN|GW-1|<GW:1,-1> - Response state:ER !!! entry:Resp -> Seq:A;30, Ba:0x51, TelegrNr:410, State:ER, set value to null
2023-07-17 20:21:16.4169|WARN|GW-1|<GW:1,-1> - Response state:ER !!! entry:Resp -> Seq:A;31, Ba:0x52, TelegrNr:410, State:ER, set value to null
2023-07-17 20:21:16.4169|WARN|GW-1|<GW:1,-1> - Response state:ER !!! entry:Resp -> Seq:A;32, Ba:0x53, TelegrNr:410, State:ER, set value to null
2023-07-17 20:21:16.4169|WARN|GW-1|<GW:1,-1> - Response state:ER !!! entry:Resp -> Seq:A;47, Ba:0x85, TelegrNr:9028, State:ER, set value to null
2023-07-17 20:21:16.4169|WARN|GW-1|<GW:1,-1> - Response state:ER !!! entry:Resp -> Seq:A;52, Ba:0x86, TelegrNr:9028, State:ER, set value to null
2023-07-17 20:21:16.4169|WARN|GW-1|<GW:1,-1> - Response state:ER !!! entry:Resp -> Seq:A;45, Ba:0x85, TelegrNr:9024, State:ER, set value to null
2023-07-17 20:21:16.4169|WARN|GW-1|<GW:1,-1> - Response state:ER !!! entry:Resp -> Seq:A;57, Ba:0x87, TelegrNr:9028, State:ER, set value to null
2023-07-17 20:21:16.4169|WARN|GW-1|<GW:1,-1> - Response state:ER !!! entry:Resp -> Seq:A;50, Ba:0x86, TelegrNr:9024, State:ER, set value to null
2023-07-17 20:21:16.4169|WARN|GW-1|<GW:1,-1> - Response state:ER !!! entry:Resp -> Seq:A;55, Ba:0x87, TelegrNr:9024, State:ER, set value to null
2023-07-17 20:21:16.4181|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:36013600001, state:Error
2023-07-17 20:21:16.4181|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:36013600002, state:Error
2023-07-17 20:21:16.4181|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:36013600003, state:Error
2023-07-17 20:21:16.4181|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:36006600001, state:Error
2023-07-17 20:21:16.4181|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:36006600002, state:Error
2023-07-17 20:21:16.4181|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:36006600003, state:Error
2023-07-17 20:21:16.4181|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:4009300001, state:Error
2023-07-17 20:21:16.4181|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:4009300002, state:Error
2023-07-17 20:21:16.4181|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:4009300003, state:Error
2023-07-17 20:21:16.4189|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:36014500001, state:Error
2023-07-17 20:21:16.4189|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:36014500002, state:Error
2023-07-17 20:21:16.4189|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:36013200001, state:Error
2023-07-17 20:21:16.4189|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:36014500003, state:Error
2023-07-17 20:21:16.4189|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:36013200002, state:Error
2023-07-17 20:21:16.4189|ERROR|GW-1|<GW:1,-1> - Missing device answer - ParameterId:36013200003, state:Error
2023-07-17 20:21:16.4232|INFO|GW-1|<GW:1,-1> - FinishBusconfig
2023-07-17 20:21:16.4542|DEBUG|GW-1|<GW:1,-1> BundleType:push, deviceVisibleReadAddresses:0x8,0x35,0x51,0x52,0x53,0x76
2023-07-17 20:21:16.4542|INFO|GW-1|<GW:1,0> Written XML, bytes:142, msg:<?xml version="1.0" encoding="utf-8"?>
    <tbreq bn="3" gw="1" ae="false" ty="push">
    <erd se="3" li="0x8,0x35,0x51,0x52,0x53,0x76" />
    </tbreq>
2023-07-17 20:21:16.4966|DEBUG|GW-1|<GW:1,-1> Detect SmartHome-System...
2023-07-17 20:21:16.4977|DEBUG|GW-1|<GW:1,-1> SmartHome = 0
2023-07-17 20:21:16.6426|INFO|GW-1|<GW:1,0> Written XML, bytes:1079, msg:<?xml version="1.0" encoding="utf-8"?>
    <tbreq bn="1000" gw="1" ae="true" ty="push">
    <ird se="B;60;59;61;62" ba="0x8" in="371" is="60" />
    <ird se="B;459;453;451" ba="0x87" in="10109" is="60" />
    <ird se="A;160" ba="0x35" in="10148" is="60" />
    <ird se="C;264;135;136;137" ba="0x76" in="135" is="60" />
    <ird se="C;264;135;136;137" ba="0x76" in="136" is="60" />
    <ird se="C;264;135;136;137" ba="0x76" in="137" is="60" />
    <ird se="A;187" ba="0x35" in="5250" is="60" />
    <ird se="A;42" ba="0x35" in="10134" is="60" />
    <ird se="B;162;155" ba="0x35" in="10161" is="60" />
    <ird se="A;389" ba="0x85" in="10159" is="60" />
    <ird se="A;435" ba="0x86" in="10159" is="60" />
    <ird se="A;481" ba="0x87" in="10159" is="60" />
    <ird se="B;214;213" ba="0x51" in="82" is="60" />
    <ird se="B;226;225" ba="0x52" in="82" is="60" />
    <ird se="B;244;243" ba="0x53" in="82" is="60" />
    <ird se="A;77" ba="0x8" in="10010" is="60" />
    <ird se="A;76" ba="0x8" in="10071" is="60" />
    <ird se="A;228" ba="0x52" in="2701" is="60" />
    <ird se="A;358" ba="0x85" in="10179" is="60" />
    <ird se="A;404" ba="0x86" in="10179" is="60" />
    </tbreq>

Das steht im Logfile des Addon, das andere verstehe ich leider nicht. Das Addon läuft jetzt ohne zu stoppen, nur gibt es keine Entitäten unter Mqtt

**Comment by Tomoene** [comment]
Konntet ihr das Problem lösen? Ich frage, weil bei mir das Gleiche auftritt.

**Comment by Tomoene** [comment]
Hi! Ich habe nur eine kleine Heizung dran hängen. Also weiß ich nicht, ob es an der Größe der Anlage liegt.

**Comment by zivillian** [comment]
@wartungsmonteur Funktioniert die Wolf Smartset App ([Android](https://play.google.com/store/apps/details?id=de.wolfheiztechnik.smartsetfacelift&hl=de&gl=US) oder [iOS](https://apps.apple.com/de/app/wolf-smartset/id1262312490)) mit deiner Anlage?

**Comment by wartungsmonteur** [comment]
Guten Morgen

Leider nein, immer noch der gleiche Fehler wie zuletzt gemeldet.

**Comment by zivillian** [comment]
Dann fürchte ich musst du dich an Wolf wenden.

**Comment by wartungsmonteur** [comment]
Ich bin Kundendiensttechniker für Wolf Heizungsanlagen

**Comment by zivillian** [comment]
@wartungsmonteur Ich kann mit deiner Antwort leider nichts anfangen. Wenn ich den Verlauf und deine Antwort richtig verstanden habe kannst du mit der offiziellen App von Wolf nicht auf deine Heizung zugreifen. Was ist deine Erwartung, was jetzt hier auf github passiert? Welche Rolle spielt es was du für einen Beruf hast? Was willst du erreichen?

Ich würde meine Software gern auch mit deiner Anlage zum Laufen bringen, aber mir fehlt leider die Zeit mich in meiner Freizeit darum zu kümmern, dass deine Anlage überhaupt so funktioniert wie vom Hersteller vorgesehen (nämlich zumindest mit der offiziellen App vom Hersteller).

Bitte versteh mich nicht falsch - ich versuche deinen Standpunkt zu verstehen und dir irgendwie weiterzuhelfen. Wenn du eine Idee oder einen Lösungsansatz für dein Problem hast, können wir hier gern drüber diskutieren, aber da dieses Projekt von Freiwilligen in ihrer Freizeit umgesetzt, erweitert und verbessert wird, musst du dich da auch entsprechend einbringen.
