### ISSUE TITLE
AddOn stoppt nach kurzer Zeit. 

### ISSUE THREAD

**Issue by Tomoene** [zivillian/ism7mqtt#67]
Hallo! Ich habe folgenden Log-Output. Was kann ich tun? Oder was mache ich falsch?

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
++ cd /app
++ parameters=/config/ism7-parameters-Wolf.json
++ '[' -f /config/ism7-parameters-Wolf.json ']'
++ echo 'Creating initial configuration /config/ism7-parameters-Wolf.json'
Creating initial configuration /config/ism7-parameters-Wolf.json
++ /app/ism7config -t /config/ism7-parameters-Wolf.json
2023-09-19 20:36:35.2177|INFO|LuCon.WebPortal.StandaloneService.NetworkConnector|Try IP-resolve for host:192.168.178.103
2023-09-19 20:36:35.2971|INFO|LuCon.WebPortal.StandaloneService.NetworkConnector|Try connect destination server -> 192.168.178.103:9092, Timeout:60000 ms
2023-09-19 20:36:37.8654|INFO|LuCon.SocketServer.SocketServerBase.GatewayContext|<GW:-1,0> Written XML, bytes:120, msg:<?xml version="1.0" encoding="utf-8"?>
    <direct-logon-request>
    <password>xxxxxxx</password>
    </direct-logon-request>
2023-09-19 20:36:38.0491|INFO|LuCon.WebPortal.StandaloneService.NetworkConnector|Got XML msg:<?xml version="1.0" encoding="utf-8"?>
    <direct-logon-response state="ok" sid="1">
    <installationname>WolfLink</installationname>
    <serialnumber>4084321922c5</serialnumber>
    <date-time>2165-165-165T20:36:36</date-time>
    <ism-softwareversion>300.10.1.300.300.1</ism-softwareversion>
    <ism-hardwareversion>3.0</ism-hardwareversion>
    <type>WOLFLink</type>
    <wlan-connected>true</wlan-connected>
    </direct-logon-response>
2023-09-19 20:36:38.0909|INFO|LuCon.WebPortal.StandaloneService.NetworkConnector|logonResponse:Errormsg:, State:ok
2023-09-19 20:36:38.1711|INFO|GW-1|<GW:1,0> Written XML, bytes:81, msg:<?xml version="1.0" encoding="utf-8"?>
    <read-systemconfig-request sid="1" />
Timeout waiting for GW
++ '[' -f /config/ism7-parameters-Wolf.json ']'
++ echo 'Parameter file creation seems to have failed. Please report to the ism7mqtt project: https://github.com/zivillian/ism7mqtt/issues/new'
Parameter file creation seems to have failed. Please report to the ism7mqtt project: https://github.com/zivillian/ism7mqtt/issues/new
++ exit -1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by zivillian** [comment]
Funktioniert die offizielle App an deiner Anlage?

**Comment by Tomoene** [comment]
Danke für die Antwort! 
Ja, die funktioniert. Und die offizielle Integration von Wolf in HA quch. Ich hab nur das Gefühl,  dass diese mein HomeAssistant langsam macht. Und grundsätzlich kann man ja nur lesen. Ich würde aber gerne die Heizung abhängig von PV-Anlage mit dem HA steuern uns hoffe noch auf eine Lösung.

**Comment by infocfc** [comment]
Vermutung: Hast Du irgendeine andere App oder Anwendung aktiv, die sich *lokal* mit Deinem Wolflink verbindet? Z.B. die Wolf App im lokalen Modus, oder SmartSet auf Windows? Das geht nämlich nicht, die Wolflink erlaubt immer nur eine lokale Verbindung. Also im Zweifel alle solche Verbindungen sicher schließen und/oder Abmelden, und dann um ganz sicher zu gehen, das Wolflink neu starten (Anlage komplett aus und wieder einschalten).

**Comment by Tomoene** [comment]
Die Wolf-App hatte ich zur Einrichtung zunächst im lokalen Modus laufen. Danach aber eigentlich nicht mehr. Aber ich versuche mich da mal abzumelden und dann starte ich Wolflink neu. Ich werde berichten. Vielen Dank schon mal.

**Comment by Tomoene** [comment]
Jetzt läuft das AddOn, legt aber kein Gerät oder Entitäten an. Hier der Log. Vielleicht kannst Du mal bitte drüber schauen:

++ /app/ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at ism7mqtt.Ism7Config.AddDevice(String ip, String ba)
   at ism7mqtt.Ism7Client.LoadInitialValuesAsync(CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 281
   at ism7mqtt.ResponseDispatcher.DispatchAsync(IResponse response, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/ResponseDispatcher.cs:line 32
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 213
++ sleep 10
++ '[' true ']'
++ echo 'Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json'
++ /app/ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at ism7mqtt.Ism7Config.AddDevice(String ip, String ba)
   at ism7mqtt.Ism7Client.LoadInitialValuesAsync(CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 281
   at ism7mqtt.ResponseDispatcher.DispatchAsync(IResponse response, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/ResponseDispatcher.cs:line 32
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 213
++ sleep 10
++ '[' true ']'
++ echo 'Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json'
Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
++ /app/ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at ism7mqtt.Ism7Config.AddDevice(String ip, String ba)
   at ism7mqtt.Ism7Client.LoadInitialValuesAsync(CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 281
   at ism7mqtt.ResponseDispatcher.DispatchAsync(IResponse response, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/ResponseDispatcher.cs:line 32
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 213
++ sleep 10
++ '[' true ']'
Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
++ echo 'Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json'
++ /app/ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at ism7mqtt.Ism7Config.AddDevice(String ip, String ba)
   at ism7mqtt.Ism7Client.LoadInitialValuesAsync(CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 281
   at ism7mqtt.ResponseDispatcher.DispatchAsync(IResponse response, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/ResponseDispatcher.cs:line 32
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 213
++ sleep 10
Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
++ '[' true ']'
++ echo 'Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json'
++ /app/ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at ism7mqtt.Ism7Config.AddDevice(String ip, String ba)
   at ism7mqtt.Ism7Client.LoadInitialValuesAsync(CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 281
   at ism7mqtt.ResponseDispatcher.DispatchAsync(IResponse response, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/ResponseDispatcher.cs:line 32
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 213
++ sleep 10
Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
++ '[' true ']'
++ echo 'Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json'
++ /app/ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at ism7mqtt.Ism7Config.AddDevice(String ip, String ba)
   at ism7mqtt.Ism7Client.LoadInitialValuesAsync(CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 281
   at ism7mqtt.ResponseDispatcher.DispatchAsync(IResponse response, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/ResponseDispatcher.cs:line 32
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 213
++ sleep 10
++ '[' true ']'
Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
++ echo 'Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json'
++ /app/ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at ism7mqtt.Ism7Config.AddDevice(String ip, String ba)
   at ism7mqtt.Ism7Client.LoadInitialValuesAsync(CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 281
   at ism7mqtt.ResponseDispatcher.DispatchAsync(IResponse response, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/ResponseDispatcher.cs:line 32
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 213
++ sleep 10
++ '[' true ']'
++ echo 'Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json'
++ /app/ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at ism7mqtt.Ism7Config.AddDevice(String ip, String ba)
   at ism7mqtt.Ism7Client.LoadInitialValuesAsync(CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 281
   at ism7mqtt.ResponseDispatcher.DispatchAsync(IResponse response, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/ResponseDispatcher.cs:line 32
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 213
++ sleep 10
Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
++ '[' true ']'
++ echo 'Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json'
++ /app/ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at ism7mqtt.Ism7Config.AddDevice(String ip, String ba)
   at ism7mqtt.Ism7Client.LoadInitialValuesAsync(CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 281
   at ism7mqtt.ResponseDispatcher.DispatchAsync(IResponse response, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/ResponseDispatcher.cs:line 32
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 213
++ sleep 10
++ '[' true ']'
++ echo 'Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json'
++ /app/ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json

**Comment by Tomoene** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
++ cd /app
++ parameters=/config/ism7-parameters-Wolf.json
++ '[' -f /config/ism7-parameters-Wolf.json ']'
++ ISM_ARGS='--hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json'
++ [[ false == \t\r\u\e ]]
++ '[' true ']'
++ echo 'Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json'
Starting ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json
++ /app/ism7mqtt --hass-id=Wolf --interval=60 -t /config/ism7-parameters-Wolf.json


Das ist der aktuelle Log. Weiter passiert nichts mehr.

**Comment by infocfc** [comment]
Da muss ich jetzt passen, das überlasse ich @zivillian. Aber wir sind in jedem Fall einen Schritt weiter.

**Comment by Tomoene** [comment]
@zivillian Meinst Du, Du könntest mal über meinen Log drüberlesen? Ich wäre Dir sehr dankbar. VG

**Comment by zivillian** [comment]
@Tomoene ja, aber ich komme da erst Ende nächster Woche zu

**Comment by Tomoene** [comment]
Ja klar! Vielen Dank schon mal.

**Comment by threadstone83** [comment]
Ich klinke mich hier auch mal mit ein. Ich habe mir ebenfalls das Add-on installiert ([hassio-addon-ism7mqtt](https://github.com/b3nn0/hassio-addon-ism7mqtt)), aber bei mir werden auch keine Geräte oder Entitäten angelegt.

**Comment by zivillian** [comment]
@threadstone83 Danke für den Hinweis. Hast du zufällig noch das Logfile direkt nach der Umstellung, bzw. kannst du den Fehler und die Lösung reproduzieren und ein Logfile erstellen?

**Comment by zivillian** [comment]
@Tomoene kannst du einmal schauen, was in der /config/ism7-parameters-Wolf.json drin steht?

**Comment by threadstone83** [comment]
> @threadstone83 Danke für den Hinweis. Hast du zufällig noch das Logfile direkt nach der Umstellung, bzw. kannst du den Fehler und die Lösung reproduzieren und ein Logfile erstellen?
> 
> EDIT: wo genau hast du das Leerzeichen entfernt? EDIT: hat sich erledigt - ich hab den Issue in hassio-addon-ism7mqtt gesehen
OK. Ich hätte es auch noch einmal versucht nachzustellen. Und ja - ich habe es dort auch platziert.
Wenn du noch etwas brauchst, sag Bescheid.

**Comment by Tomoene** [comment]
@zivillian Klar, bitteschön:

{
  "Devices": [
    {
      "ReadBusAddress": "0x00",
      "DeviceTemplateId": 190000,
      "Parameter": [
        190000,
        190001,
        190002,
        190003,
        190004,
        190007,
        190011,
        190012,
        190014,
        190015,
        190016,
        190019,
        190020,
        190021
      ]
    },
    {
      "ReadBusAddress": "0x8",
      "DeviceTemplateId": 80000,
      "Parameter": [
        80062,
        80063,
        80084,
        80085,
        80088,
        80000,
        80001,
        80002,
        80004,
        80005,
        80006,
        80007,
        80009,
        80010,
        80011,
        80012,
        80014,
        80015,
        80016,
        80017,
        80018,
        80019,
        80020,
        80021,
        80023,
        80024,
        80025,
        80026,
        80027,
        80028,
        80029,
        80030,
        80031,
        80032,
        80033,
        80034,
        80035,
        80036,
        80037,
        80038,
        80041,
        80042,
        80061
      ]
    },
    {
      "ReadBusAddress": "0x35",
      "DeviceTemplateId": 30000,
      "Parameter": [
        30011,
        30016,
        30017,
        30018,
        30019,
        30020,
        30021,
        30022,
        30024,
        30025,
        30026,
        30027,
        30028,
        30030,
        30031,
        30032,
        30033,
        30035,
        30066,
        30067,
        30068,
        30072,
        300016,
        300017,
        300023,
        300024,
        300025,
        300026,
        300027,
        300028,
        300029,
        300030,
        300031,
        30000,
        30001,
        30002,
        30003,
        30004,
        30008
      ]
    },
    {
      "ReadBusAddress": "0x75",
      "DeviceTemplateId": 30000,
      "Parameter": [
        30000
      ]
    },
    {
      "ReadBusAddress": "0x51",
      "DeviceTemplateId": 40000,
      "Parameter": [
        40093,
        40001,
        40002,
        40004,
        40005,
        40006,
        40007,
        40009,
        40010,
        40011,
        40014,
        40027,
        40028,
        40070
      ]
    },
    {
      "ReadBusAddress": "0x15",
      "DeviceTemplateId": 0,
      "Parameter": []
    },
    {
      "ReadBusAddress": "0x75",
      "DeviceTemplateId": 20000,
      "Parameter": [
        300000,
        300001,
        300002,
        300003,
        300004,
        300005,
        300006,
        20000,
        300007,
        20001,
        300008,
        20002,
        300009,
        20003,
        300010,
        20004,
        20005,
        20006,
        20009,
        20012,
        20013
      ]
    }
  ]
}

**Comment by zivillian** [comment]
@Tomoene du hast ein ungültiges Gerät in der config - das Problem hatten wir [schon einmal](https://github.com/zivillian/ism7mqtt/issues/64#issuecomment-1653993168). Wenn du deine parameter.json anpasst sollte es funktionieren. In der nächsten Version ist der Fehler schon behoben.

**Comment by Tomoene** [comment]
Perfekt! Läuft alles! Vielen Dank für Deine Mühe!
