### ISSUE TITLE
ism7mqtt unexpectedly quit with return code 137

### ISSUE THREAD

**Issue by Hafenmeister31** [zivillian/ism7mqtt#95]
Hi there,

happening in both of my instances since today at 5:00. I don't know if anybode else has the same error ?
Here's an excerpt from the log:

```
< <?xml version="1.0" encoding="utf-8"?><direct-logon-response state="ok" sid=""><installationname>WolfLink</installationname><serialnumber>9c956e5f2f60</serialnumber><date-time>2024-02-12T12:32:09</date-time><ism-softwareversion>300.10.1.300.300.1</ism-softwareversion><ism-hardwareversion>3.0</ism-hardwareversion><type>WOLFLink</type></direct-logon-response>
System.InvalidOperationException: There is an error in XML document (1, 40).
 ---> System.InvalidOperationException: <direct-logon-response xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderTelegramBundleResp.Read6_tbres()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at ism7mqtt.Ism7Client.Deserialize(PayloadType type, Stream data) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 390
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 211
Starting ism7mqtt --hass-id=WolfHaus --interval=60 --ipAddress=192.168.XX.62 -t /config/ism7-parameters-WolfHaus.json -d
System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at ism7mqtt.Ism7Client.ConnectAsync(CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 86
   at ism7mqtt.Ism7Client.RunAsync(String password, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 50
   at ism7mqtt.Program.Main(String[] args) in /app/ism7mqtt/Program.cs:line 136
Unhandled exception. System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at ism7mqtt.Ism7Client.ConnectAsync(CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 86
   at ism7mqtt.Ism7Client.RunAsync(String password, CancellationToken cancellationToken) in /app/ism7mqtt/ISM7/Ism7Client.cs:line 50
   at ism7mqtt.Program.Main(String[] args) in /app/ism7mqtt/Program.cs:line 136
   at ism7mqtt.Program.<Main>(String[] args)
ism7mqtt unexpectedly quit with return code 134
/run.sh: line 26:  1021 Aborted                 (core dumped) /app/ism7mqtt $ISM_ARGS
Starting ism7mqtt --hass-id=WolfWohnung --interval=60 --ipAddress=192.168.XX.61 -t /config/ism7-parameters-WolfWohnung.json -d
Starting ism7mqtt --hass-id=WolfHaus --interval=60 --ipAddress=192.168.XX.62 -t /config/ism7-parameters-WolfHaus.json -d
ism7mqtt unexpectedly quit with return code 137
/run.sh: line 26:  1036 Killed                  /app/ism7mqtt $ISM_ARGS
> <?xml version="1.0" encoding="utf-16"?><direct-logon-request xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><password>SECRET</password></direct-logon-request>
ism7mqtt unexpectedly quit with return code 137
/run.sh: line 26:  1050 Killed                  /app/ism7mqtt $ISM_ARGS
```

**Comment by zivillian** [comment]
> Received an unexpected EOF or 0 bytes from the transport stream.
This is your ISM just closing the connection. I had this a few times after some minutes it worked again.

**Comment by Hafenmeister31** [comment]
True, it took a day, but now it works again like it should. 👍
